// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANqyN9-kSvqFo4bC8m7ntIBNXf9IJp13U',
    appId: '1:224925040236:web:6ae372a8cee35588c0e249',
    messagingSenderId: '224925040236',
    projectId: 'superdash-ee609',
    authDomain: 'superdash-ee609.firebaseapp.com',
    databaseURL: 'https://superdash-ee609-default-rtdb.firebaseio.com',
    storageBucket: 'superdash-ee609.firebasestorage.app',
    measurementId: 'G-6GEL0B6384',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDilN9zOu7JabNUjksoucjfZyHOsTrD2WU',
    appId: '1:224925040236:android:218f4371b79aa79bc0e249',
    messagingSenderId: '224925040236',
    projectId: 'superdash-ee609',
    databaseURL: 'https://superdash-ee609-default-rtdb.firebaseio.com',
    storageBucket: 'superdash-ee609.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYjZkT5lYWMERW3Nub2uBlqsFN1tlmhTM',
    appId: '1:224925040236:ios:442fb362bf3d4272c0e249',
    messagingSenderId: '224925040236',
    projectId: 'superdash-ee609',
    databaseURL: 'https://superdash-ee609-default-rtdb.firebaseio.com',
    storageBucket: 'superdash-ee609.firebasestorage.app',
    iosBundleId: 'com.ext.superdash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYjZkT5lYWMERW3Nub2uBlqsFN1tlmhTM',
    appId: '1:224925040236:ios:184052306f6f259cc0e249',
    messagingSenderId: '224925040236',
    projectId: 'superdash-ee609',
    databaseURL: 'https://superdash-ee609-default-rtdb.firebaseio.com',
    storageBucket: 'superdash-ee609.firebasestorage.app',
    iosBundleId: 'com.example.dashRun',
  );
}
